const CHANGE_INPUT = 'CHANGE_INPUT';
const POPULATE_LIST = 'POPULATE_LIST';
const ON_REFRESH = 'ON_REFRESH';
const ON_REFRESH_END = 'ON_REFRESH_END';
export {CHANGE_INPUT, POPULATE_LIST, ON_REFRESH, ON_REFRESH_END};
